server:
  port: 8020
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/pedrojhrossi/microservices-yt
          search-paths: config-data
  application:
    name: config-service
